apiVersion: apps/v1
kind: Deployment
metadata:
  name: saas-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: saas
  template:
    metadata:
      labels:
        app: saas
    spec:
      containers:
      - name: app
        image: nginx